volumes:
  - name: kafka-cert
    secret:
    secretName: astra-indexing-worker-dev.kafka.prod.tls.astranet.services
volumeMounts:
  - name: kafka-cert
    mountPath: /certs/chainindexing.kafka.dev
specAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
serviceAccount: astra-indexing