blockchain:
  bonding_denom: "aastra"
  account_address_prefix: "astra"
  account_pubkey_prefix: "astrapub"
  validator_address_prefix: "astraval"
  validator_pub_key_prefix: "astraval"
  con_node_address_prefix: "astravalcons"
  con_node_pubkey_prefix: "astravalconspub"

index_service:
  enable: true
  # Mode of index service, possible values: EVENT_STORE, TENDERMINT_DIRECT
  # EVENT_STORE mode: synced blocks are parsed to events and persist to event store. Projections will replay events from
  # event store.
  # TENDERMINT_DIRECT mode: synced blocks are parsed to events and are replayed directly by projections.
  mode: "TENDERMINT_DIRECT"
  # Number of sync jobs running in parallel
  window_size: 10
  concurrency: 10
  projection:
    enables: [
        "Account",
        # "AccountMessage",
        "AccountTransaction",
        "Block",
        # "ChainStats",
        "Proposal",
        "Transaction",
        "Validator",
        "ValidatorStats",
        # "IBCChannel",
        # "IBCChannelTxMsgTrace",
        # "IBCChannelMessage",
    ]
  cronjob:
    enables: [ ]
  cosmos_version_enabled_height:
    v0_45_7: 0
  github_api:
    # For `username` and `token`, please generate your own `Personal access tokens` in Github.
    username: ""
    token: ""
    migration_repo_ref: ""

http_service:
  enable: true
  listening_address: "0.0.0.0:8080"
  route_prefix: "/"
  # A list of origins a cross-domain request is allowed to be requested from
  # Default value '[]' disables CORS support
  # Use '["*"]' to allow request from any origin
  # cors_allowed_origins: [ "*" ]
  cors_allowed_methods: [ "HEAD", "GET" ]
  cors_allowed_headers: [ "Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time" ]

tendermint_app:
  http_rpc_url: "https://cosmos.astranaut.io"
  insecure: false
  # When strict_genesis_parsing enabled, genssi parsing will reject any non-Cosmos SDK built-in module
  # inside genesis file.
  strict_genesis_parsing: false

cosmos_app:
  http_rpc_url: "https://api.astranaut.io"
  insecure: false

blockscout_app:
  http_rpc_url: "http://blockscout.tiki.services"
  insecure: false

debug:
  pprof_enable: true
  pprof_listening_address: "0.0.0.0:3000"

postgres:
  pool_max_conns: 100
  pool_min_conns: 0
  pool_max_conn_life_time: "1h"
  pool_max_conn_idle_time: "30m"
  pool_health_check_interval: "1m"

logger:
  # Comma separated log levels. possible values: debug,info,error,panic
  level: "error"
  color: false

prometheus:
  enable: true
  export_path: "/"
  port: "9090"

cronjobstats:
  enable: true

# Custom config for example
server_github_api:
  migration_repo_ref: ""