package evm

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test4Bytes(t *testing.T) {
	util, err := NewEvmUtils()
	if err != nil {
		panic(err)
	}

	//0xc0331b3e
	res, err := util.GetSignature("0xc0331b3e")
	if err != nil {
		panic(err)
	}
	fmt.Println("hoank", res)
}

func TestGetSignatureFromData(t *testing.T) {
	assert := assert.New(t)

	util, err := NewEvmUtils()
	if err != nil {
		panic(err)
	}
	data := "0q7S1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSWzhIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQVbZvQpCuU8VUVDSeyAd243bdr5ljiPA3bK7aUm/VuQVdhajtudaHAI7ltLe1GHQeZchiXxaXAq2Ez+6ErCpJRscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
	signature := util.GetSignatureFromData(data)
	assert.Equal(signature, "exchange")

	data = "sTSjZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAqJyv7Z/fSgPMmUkRT3r1XgqKDY4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiGyYt2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZHm5ZA=="
	signature = util.GetSignatureFromData(data)
	assert.Equal(signature, "grantLockedReward")
}
