name: Chainindexing development deployment
on:
  push:
    branches: ['dev']
jobs:
  build-chainindexing:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      ingressHost: "chainindexing.dev.astranet.services"
      replicas: "1"
      servicePort: "8080"
    secrets: inherit  

name: Chainindexing-worker development deployment
on:
  push:
    branches: ['dev']
jobs:
  build-chainindexing:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      replicas: "1"
    secrets: inherit  