name: Development deployment
on:
  push:
    branches: ['dev']

jobs:
  build-image:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      ingressHost: "chainindexing.dev.astranet.services"
      replicas: "1"
      servicePort: "8080"
    with:
      ingressEnabled: "yes"
      ingressHost: "chainindexing-worker.dev.astranet.services"
      replicas: "1"
      servicePort: "8080"  
    secrets: inherit