name: Production deployment
on:
  push:
    branches: ['main']

jobs:
  build-chainindexing:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      ingressHost: "chainindexing.prod.astranet.services"
      replicas: "2"
      servicePort: "8080"
    secrets: inherit  
  build-chainindexing-worker:    
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      workloadName: astra-indexing-worker-prod
      ingressEnabled: "yes"
      ingressHost: "chainindexing-worker.prod.astranet.services"
      replicas: "1"
      kafkaCert: "true"
      kafkaEnv: "prod"
    secrets: inherit